In [1]:
import matplotlib.pyplot as plt
import pandas as pd
from sktime.classification.kernel_based import RocketClassifier
import numpy as np

In [63]:
df0 = pd.read_csv("ProjectData\\0.csv", index_col="timeOffset")
df1 = pd.read_csv("ProjectData\\1.csv", index_col="timeOffset")
df2 = pd.read_csv("ProjectData\\2.csv", index_col="timeOffset")
df3 = pd.read_csv("ProjectData\\3.csv", index_col="timeOffset")
df4 = pd.read_csv("ProjectData\\4.csv", index_col="timeOffset")
df5 = pd.read_csv("ProjectData\\5.csv", index_col="timeOffset")
df6 = pd.read_csv("ProjectData\\6.csv", index_col="timeOffset")
df7 = pd.read_csv("ProjectData\\7.csv", index_col="timeOffset")
df8 = pd.read_csv("ProjectData\\8.csv", index_col="timeOffset")
df9 = pd.read_csv("ProjectData\\9.csv", index_col="timeOffset")
df10 = pd.read_csv("ProjectData\\10.csv", index_col="timeOffset")
df0.index.name = None
df1.index.name = None
df2.index.name = None
df3.index.name = None
df4.index.name = None
df5.index.name = None
df6.index.name = None
df7.index.name = None
df8.index.name = None
df9.index.name = None
df10.index.name = None
print(df10.index)

Float64Index([           0.0, 0.008999999613,  0.03400000185,  0.04600000009,
               0.05000000075,   0.0549999997,  0.05900000036,  0.06300000101,
               0.06700000167,  0.07100000232,
              ...
                 5.010911107,     5.01991111,    5.027911127,    5.031911135,
                 5.035911143,    5.039911091,    5.044911087,    5.052911103,
                 5.060911119,    5.069911122],
             dtype='float64', length=43476)

In [64]:
# quick brown fox 157-162 el za, rest 86-91 (+71)
#cat 163 (+72)
df=[]
name_y=[]
for i in range(11,71):
#     df.append(df0.loc[df0['SampleNum'] == (i)].reset_index(drop=True))
#     name_y.append(0)
    df.append((df1.loc[df1['SampleNum'] == i]).reset_index(drop=True))
#     df1.reset_index(drop=True)
    name_y.append(1)
#     df.append(df2.loc[df2['SampleNum'] == (i)].reset_index(drop=True))
#     name_y.append(2)
    df.append(df3.loc[df3['SampleNum'] == i].reset_index(drop=True))
    name_y.append(3)
    df.append(df4.loc[df4['SampleNum'] == i].reset_index(drop=True))
    name_y.append(4)
    df.append(df5.loc[df5['SampleNum'] == i].reset_index(drop=True))
    name_y.append(5)
    df.append(df6.loc[df6['SampleNum'] == i].reset_index(drop=True))
    name_y.append(6)
    df.append(df7.loc[df7['SampleNum'] == i].reset_index(drop=True))
    name_y.append(7)
    df.append(df8.loc[df8['SampleNum'] == i].reset_index(drop=True))
    name_y.append(8)
    df.append(df9.loc[df9['SampleNum'] == i].reset_index(drop=True))
    name_y.append(9)
    df.append(df10.loc[df10['SampleNum'] == i].reset_index(drop=True))
    name_y.append(10)

In [65]:
df[0].head()

,altitude,azimuth,force,av force per stroke,av force per sample,x,y,speed,strokeNum,av speed per stroke,SampleNum,av speed per sample,strokes in sample,sampleTarget,character count,user,unique number of strokes
0,0.856454,0.864268,0.134,0.552933,0.413669,225.305176,81.651245,0.000000,1,412.431796,11,262.632321,12,carnivorous,11,Eylul,NaN
1,0.856454,0.864268,0.232,0.552933,0.413669,225.305176,79.999634,50.048828,1,412.431796,11,262.632321,12,carnivorous,11,Eylul,NaN
2,0.856454,0.872513,0.337,0.552933,0.413669,225.251160,77.034241,50.269237,1,412.431796,11,262.632321,12,carnivorous,11,Eylul,NaN
3,0.856454,0.872513,0.391,0.552933,0.413669,223.864746,76.446167,75.298947,1,412.431796,11,262.632321,12,carnivorous,11,Eylul,NaN
4,0.856454,0.872513,0.440,0.552933,0.413669,221.542053,76.371094,136.700424,1,412.431796,11,262.632321,12,carnivorous,11,Eylul,NaN

In [66]:
data_df = pd.DataFrame(columns=["altitude", "azimuth", "force", "x", "y", "speed", "strokeNum"])
# data_df = pd.DataFrame(columns=["altitude", "azimuth", "force", "x", "y", "speed"])
# data_df = pd.DataFrame(columns=["x", "y"])
for d in df:
    data_df.loc[len(data_df.index)]= [d['altitude'].squeeze(), d['azimuth'].squeeze(),d['force'].squeeze(),d['x'].squeeze(),d['y'].squeeze(),d['speed'].squeeze(),d['strokeNum'].squeeze()]
    #      data_df.loc[len(data_df.index)]= [d['altitude'].squeeze(), d['azimuth'].squeeze(),d['force'].squeeze(),d['x'].squeeze(),d['y'].squeeze(),d['speed'].squeeze()]
#     data_df.loc[len(data_df.index)]= [d['x'].squeeze(),d['y'].squeeze()]
    
# print(type(data_df[0]))
print(data_df.dtypes)
# data_df.astype(pd.Series).dtypes
print(data_df['altitude'].dtypes)
data_df.head()

altitude     object
azimuth      object
force        object
x            object
y            object
speed        object
strokeNum    object
dtype: object
object

,altitude,azimuth,force,x,y,speed,strokeNum
0,0 0.856454 1 0.856454 2 0.85645...,0 0.864268 1 0.864268 2 0.87251...,0 0.134 1 0.232 2 0.337 3 ...,0 225.305176 1 225.305176 2 225...,0 81.651245 1 79.999634 2 77...,0 0.000000 1 50.048828 2 50...,0 1 1 1 2 1 3 1 4 ...
1,0 0.966830 1 0.966830 2 0.96683...,0 2.734794 1 2.734794 2 2.73479...,0 0.576 1 0.920 2 1.304 3 ...,0 445.744934 1 449.039917 2 451...,0 98.392578 1 96.941162 2 95...,0 0.000000 1 171.451858 2 198...,0 1 1 1 2 1 3 1 4 ...
2,0 0.930949 1 0.930949 2 0.93094...,0 0.912972 1 0.912972 2 0.91297...,0 0.437 1 0.439 2 0.476 3 ...,0 286.649475 1 285.191040 2 282...,0 111.768127 1 109.591003 2 108...,0 0.000000 1 327.559660 2 310...,0 1 1 1 2 1 3 1 4 ...
3,0 0.769806 1 0.769806 2 0.76980...,0 0.857556 1 0.857556 2 0.85755...,0 0.142 1 0.144 2 0.153 3 ...,0 239.367371 1 238.377075 2 237...,0 101.758362 1 100.231873 2 98...,0 0.000000 1 454.893816 2 426...,0 1 1 1 2 1 3 1 4 ...
4,0 0.761298 1 0.761298 2 0.76129...,0 0.586709 1 0.586709 2 0.58670...,0 0.423 1 0.487 2 0.558 3 ...,0 317.204590 1 317.204590 2 317...,0 99.180847 1 96.740967 2 94...,0 0.000000 1 143.522367 2 148...,0 1 1 1 2 1 3 1 4 ...

In [67]:
X_train = data_df.loc[:71,:]
y_train = name_y[:72]
X_test = data_df.loc[72:,:]
y_test = name_y[72:]
y_train = np.asarray(y_train)
y_test = np.asarray(y_test)

In [68]:
from sktime.transformations.panel.rocket import Rocket
from sklearn.linear_model import RidgeClassifierCV

In [69]:
from sktime.transformations.panel.padder import PaddingTransformer

In [70]:
my_padded_rocket = PaddingTransformer() * RocketClassifier()
my_padded_rocket.fit(X_train, y_train)

ClassifierPipeline(classifier=RocketClassifier(),
                   transformers=[PaddingTransformer()])

In [71]:
y_pred = my_padded_rocket.predict(X_test)

TypeError: X must be in an sktime compatible format, of scitype Series, Panel or Hierarchical, for instance a pandas.DataFrame with sktime compatible time indices, or with MultiIndex and last(-1) level an sktime compatible time index. Allowed compatible mtype format specifications are: ['pd.Series', 'pd.DataFrame', 'np.ndarray', 'nested_univ', 'numpy3D', 'pd-multiindex', 'df-list', 'pd_multiindex_hier'] . See the data format tutorial examples/AA_datatypes_and_datasets.ipynb. If you think the data is already in an sktime supported input format, run sktime.datatypes.check_raise(data, mtype) to diagnose the error, where mtype is the string of the type specification you want. Error message for checked mtypes, in format [mtype: message], as follows: [pd.DataFrame: <class 'pandas.core.indexes.multi.MultiIndex'> is not supported for X, use one of (<class 'pandas.core.indexes.range.RangeIndex'>, <class 'pandas.core.indexes.period.PeriodIndex'>, <class 'pandas.core.indexes.datetimes.DatetimeIndex'>) or integer index instead.]  [pd.Series: X must be a pandas.Series, found <class 'pandas.core.frame.DataFrame'>]  [np.ndarray: X must be a numpy.ndarray, found <class 'pandas.core.frame.DataFrame'>]  [xr.DataArray: X must be a xarray.DataArray, found <class 'pandas.core.frame.DataFrame'>]  [dask_series: X must be a dask DataFrame, found <class 'pandas.core.frame.DataFrame'>]  [df-list: X must be list of pd.DataFrame, found <class 'pandas.core.frame.DataFrame'>]  [numpy3D: X must be a numpy.ndarray, found <class 'pandas.core.frame.DataFrame'>]  [pd-multiindex: The (time) index of X must be sorted monotonically increasing, but found: MultiIndex([( 72,   0),
            ( 72,   1),
            ( 72,   2),
            ( 72,   3),
            ( 72,   4),
            ( 72,   5),
            ( 72,   6),
            ( 72,   7),
            ( 72,   8),
            ( 72,   9),
            ...
            (539, 340),
            (539, 341),
            (539, 342),
            (539, 343),
            (539, 344),
            (539, 345),
            (539, 346),
            (539, 347),
            (539, 348),
            (539, 349)],
           names=[None, 'timepoints'], length=220589)]  [nested_univ: X All columns must be object, found <class 'pandas.core.frame.DataFrame'>]  [dask_panel: X must be a dask DataFrame, found <class 'pandas.core.frame.DataFrame'>]  [pd_multiindex_hier: X must have a MultiIndex with 3 or more levels, found 2]  [dask_hierarchical: X must be a dask DataFrame, found <class 'pandas.core.frame.DataFrame'>]

In [ ]:
print(y_pred)

In [ ]:
print(y_test)
print(name_y)

In [ ]:
from sklearn.metrics import precision_score, accuracy_score

accuracy_score(y_test, y_pred)

In [ ]:
from sktime.registry import all_estimators

# search for all classifiers which can handle unequal length data. This may give some
# UserWarnings if soft dependencies are not installed.
all_estimators(
    filter_tags={"capability:unequal_length": True}, estimator_types="classifier"
)

In [ ]:
# clf = PaddingTransformer() * TemporalDictionaryEnsemble(
#     n_parameter_samples=11,
#     max_ensemble_size=3,
#     randomly_selected_params=5,
# ) 
# clf.fit(X_train, y_train)

In [ ]:
# y_pred = clf.predict(X_test)

In [ ]:
# print(y_pred)
# print(y_test)

In [ ]:
# from sktime.classification.distance_based import KNeighborsTimeSeriesClassifier

In [ ]:
# clf = PaddingTransformer() *KNeighborsTimeSeriesClassifier(distance="euclidean")
# clf.fit(X_train, y_train)

In [ ]:
# y_pred = clf.predict(X_test)
# print(y_pred)
# print(y_test)

In [ ]:
# from sktime.classification.distance_based import ProximityForest
# clf = PaddingTransformer() *KNeighborsTimeSeriesClassifier(distance="euclidean")
# clf.fit(X_train, y_train)
# y_pred = clf.predict(X_test)
# print(y_pred)
# print(y_test)

In [ ]:
from sktime.transformations.panel.rocket import MiniRocketMultivariate
trf = PaddingTransformer() * MiniRocketMultivariate(num_kernels=512)

In [ ]:
trf.fit(X_train)
X_train_tr = trf.transform(X_train) 
X_test_tr = trf.transform(X_test)

In [ ]:
classifier = RidgeClassifierCV(alphas=np.logspace(-3, 3, 10), normalize=True)
classifier.fit(X_train_tr, y_train)

In [ ]:
y_pred = classifier.predict(X_test_tr)
print(y_pred)
print(y_test)
accuracy_score(y_test, y_pred)